labs/stox/config/routes.rb
Stox::Application.routes.draw do

  root :to => 'home#index'
  resources :stocks
  

end

labs/stox/app/models/stock.rb
# == Schema Information
#
# Table name: stocks
#
#  id         :integer          not null, primary key
#  symbol     :string(255)
#  quotes     :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Stock < ActiveRecord::Base
end

labs/stox/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

labs/stox/app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
  end  

  def new
    @stock = Stock.new

  end

  def create
    raise params.inspect
  end



end  

labs/stox/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stox</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
  <%= link_to "Home", root_path %>
  <%= link_to "Stocks", stocks_path %>
  <%= link_to "New Stock", new_stock_path %>
</nav>

<%= yield %>

</body>
</html>

labs/stox/app/views/stocks/index.html.erb
Nothing here

labs/stox/app/views/stocks/new.html.erb
<%= form_for @stock do |f| %>
  <div class="field">
    <%= f.label :symbol %>
    <%= f.text_field :symbol %>
  </div>
  <div class="field">
    <%= label_tag 'Enter number of quotes you want' %>
    <%= number_field_tag 'number' %>
  </div>
  <div class="field">
    <%= f.submit %>
  </div>
<% end %>