labs/alienvspredator/config/routes.rb
Alienvspredator::Application.routes.draw do
  
  get '/about' => 'home#about'
  get '/faq' => 'home#faq'
  get '/creaturetypes' => 'creature_types#index'
  post '/creaturetypes' => 'creature_types#create'
  get '/creaturetypes/:id' => 'creature_types#show', :as => 'creaturetype' #singular vs. creaturetypeS above
  get '/search' => 'creature_types#search'

  root :to => 'home#index'

end

labs/alienvspredator/app/models/creature.rb
# == Schema Information
#
# Table name: creatures
#
#  id               :integer          not null, primary key
#  name             :string(255)
#  weapon           :string(255)
#  password_digest  :string(255)
#  creature_type_id :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Creature < ActiveRecord::Base
  has_secure_password
  belongs_to :creature_type
  # has messages!
  has_many :sent_messages, :class_name => 'Message', :foreign_key => 'sender_id'
  has_many :received_messages, :class_name => 'Message', :foreign_key => 'receiver_id'
end

labs/alienvspredator/app/models/creature_type.rb
# == Schema Information
#
# Table name: creature_types
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CreatureType < ActiveRecord::Base
  has_many :creatures
end

labs/alienvspredator/app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id           :integer          not null, primary key
#  message_text :text
#  sender_id    :integer
#  receiver_id  :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Message < ActiveRecord::Base
  belongs_to :sender, :class_name => 'Creature', :foreign_key => 'sender_id'
  belongs_to :receiver, :class_name => 'Creature', :foreign_key => 'receiver_id'
end

labs/alienvspredator/app/controllers/creature_types_controller.rb
class CreatureTypesController < ApplicationController
  def index
    @creature_types = CreatureType.page(params[:page])
  end

  def create
    name = params[:name]
    @ct = CreatureType.create(:name => name)
  end

  def show
    id = params[:id]
    @creaturetype = CreatureType.find(id)
  end

  def search
    name = params[:name]
    @creature_types = CreatureType.where(:name => name)
  end
end

labs/alienvspredator/app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end

  def about
  end

  def faq
  end

end

labs/alienvspredator/app/views/home/about.html.erb
<% content_for :submenu do %>
  <%= link_to "About", about_path %>
  <%= link_to "FAQ", faq_path %>
<% end %>

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras nec neque sapien, in commodo risus. In ligula est, auctor a vestibulum ullamcorper, interdum id est. Proin aliquam sodales enim, nec vulputate metus euismod vel. Morbi vitae purus id nisi suscipit bibendum facilisis ac felis. Donec fringilla, metus vitae sollicitudin sagittis, elit tellus lobortis sapien, non faucibus nulla mauris eu odio. Sed velit leo, viverra id eleifend eu, elementum ut metus. Nullam eleifend risus et diam scelerisque in venenatis nisl semper. Curabitur eget elit justo. Aenean laoreet nunc et magna rhoncus pretium. Sed sed nisl at ante molestie lacinia ac ut lectus. Etiam semper quam et diam accumsan sodales.

In ullamcorper metus sed ligula interdum vehicula. Nam eu nisl eget diam luctus aliquet ornare et leo. Sed vitae egestas turpis. Pellentesque ullamcorper porttitor elit, non laoreet felis tempus nec. Etiam mollis commodo urna, vitae faucibus dui dictum et. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vel mauris tellus. Nulla sed velit vel mauris gravida vehicula. Quisque dui lorem, euismod ut ornare et, venenatis ultricies sapien. Morbi laoreet, ante eu commodo faucibus, ipsum sapien adipiscing tortor, sed facilisis justo velit ut velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Suspendisse potenti. Maecenas leo dui, condimentum vel ornare ac, porttitor sit amet arcu. Aliquam imperdiet faucibus dapibus. Vivamus eu velit nunc, sit amet facilisis quam. Donec eleifend elementum luctus. Donec a metus ut metus aliquam scelerisque at sed libero. Mauris ante sapien, imperdiet id venenatis ac, mattis in est. Mauris condimentum, mi in gravida congue, mi tortor congue nulla, in lacinia purus neque vel diam. Fusce faucibus, tellus ac dictum imperdiet, dui nisi euismod purus, eget dapibus diam quam venenatis lectus. Fusce tempus iaculis aliquam. Sed non nisl ut ipsum facilisis adipiscing et in urna. Maecenas quis vestibulum turpis. Sed faucibus urna sed mauris iaculis volutpat. Aliquam sed est tellus, ut eleifend mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In justo sem, porta nec lacinia quis, elementum ac massa.

Nunc at nisi augue, et iaculis nisi. Integer condimentum blandit neque eu eleifend. Donec faucibus, enim vel fermentum tempus, purus orci blandit metus, non rhoncus mi sapien ac lacus. Donec congue dolor a neque pretium tempor. Ut vitae dui enim, euismod tempus risus. Nulla iaculis faucibus consequat. Quisque sed ornare nisl.

Pellentesque rutrum metus ac massa gravida pharetra nec et ante. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec eu enim vel dolor commodo mollis. Duis facilisis, erat in elementum elementum, massa sem condimentum nisl, a commodo augue odio sit amet neque. Etiam vitae nunc libero. Ut ac diam quis augue consequat imperdiet in nec ipsum. Vestibulum pulvinar tincidunt justo, non sagittis nisl suscipit ut. Vivamus fermentum nibh non justo convallis pretium. Aliquam rutrum iaculis convallis. Nulla pulvinar convallis orci porta ornare. Mauris vitae nulla purus, vel viverra libero. Aliquam erat volutpat.

labs/alienvspredator/app/views/home/faq.html.erb
<% content_for :submenu do %>
  <%= link_to "About", about_path %>
  <%= link_to "FAQ", faq_path %>
<% end %>

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras nec neque sapien, in commodo risus. In ligula est, auctor a vestibulum ullamcorper, interdum id est. Proin aliquam sodales enim, nec vulputate metus euismod vel. Morbi vitae purus id nisi suscipit bibendum facilisis ac felis. Donec fringilla, metus vitae sollicitudin sagittis, elit tellus lobortis sapien, non faucibus nulla mauris eu odio. Sed velit leo, viverra id eleifend eu, elementum ut metus. Nullam eleifend risus et diam scelerisque in venenatis nisl semper. Curabitur eget elit justo. Aenean laoreet nunc et magna rhoncus pretium. Sed sed nisl at ante molestie lacinia ac ut lectus. Etiam semper quam et diam accumsan sodales.

In ullamcorper metus sed ligula interdum vehicula. Nam eu nisl eget diam luctus aliquet ornare et leo. Sed vitae egestas turpis. Pellentesque ullamcorper porttitor elit, non laoreet felis tempus nec. Etiam mollis commodo urna, vitae faucibus dui dictum et. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vel mauris tellus. Nulla sed velit vel mauris gravida vehicula. Quisque dui lorem, euismod ut ornare et, venenatis ultricies sapien. Morbi laoreet, ante eu commodo faucibus, ipsum sapien adipiscing tortor, sed facilisis justo velit ut velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Suspendisse potenti. Maecenas leo dui, condimentum vel ornare ac, porttitor sit amet arcu. Aliquam imperdiet faucibus dapibus. Vivamus eu velit nunc, sit amet facilisis quam. Donec eleifend elementum luctus. Donec a metus ut metus aliquam scelerisque at sed libero. Mauris ante sapien, imperdiet id venenatis ac, mattis in est. Mauris condimentum, mi in gravida congue, mi tortor congue nulla, in lacinia purus neque vel diam. Fusce faucibus, tellus ac dictum imperdiet, dui nisi euismod purus, eget dapibus diam quam venenatis lectus. Fusce tempus iaculis aliquam. Sed non nisl ut ipsum facilisis adipiscing et in urna. Maecenas quis vestibulum turpis. Sed faucibus urna sed mauris iaculis volutpat. Aliquam sed est tellus, ut eleifend mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In justo sem, porta nec lacinia quis, elementum ac massa.

Nunc at nisi augue, et iaculis nisi. Integer condimentum blandit neque eu eleifend. Donec faucibus, enim vel fermentum tempus, purus orci blandit metus, non rhoncus mi sapien ac lacus. Donec congue dolor a neque pretium tempor. Ut vitae dui enim, euismod tempus risus. Nulla iaculis faucibus consequat. Quisque sed ornare nisl.

Pellentesque rutrum metus ac massa gravida pharetra nec et ante. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec eu enim vel dolor commodo mollis. Duis facilisis, erat in elementum elementum, massa sem condimentum nisl, a commodo augue odio sit amet neque. Etiam vitae nunc libero. Ut ac diam quis augue consequat imperdiet in nec ipsum. Vestibulum pulvinar tincidunt justo, non sagittis nisl suscipit ut. Vivamus fermentum nibh non justo convallis pretium. Aliquam rutrum iaculis convallis. Nulla pulvinar convallis orci porta ornare. Mauris vitae nulla purus, vel viverra libero. Aliquam erat volutpat.

labs/alienvspredator/app/views/home/index.html.erb
<% content_for :submenu do %>
  <%= link_to "About", about_path %>
  <%= link_to "FAQ", faq_path %>
<% end %>

<i class="icon-search"></i>

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras nec neque sapien, in commodo risus. In ligula est, auctor a vestibulum ullamcorper, interdum id est. Proin aliquam sodales enim, nec vulputate metus euismod vel. Morbi vitae purus id nisi suscipit bibendum facilisis ac felis. Donec fringilla, metus vitae sollicitudin sagittis, elit tellus lobortis sapien, non faucibus nulla mauris eu odio. Sed velit leo, viverra id eleifend eu, elementum ut metus. Nullam eleifend risus et diam scelerisque in venenatis nisl semper. Curabitur eget elit justo. Aenean laoreet nunc et magna rhoncus pretium. Sed sed nisl at ante molestie lacinia ac ut lectus. Etiam semper quam et diam accumsan sodales.

In ullamcorper metus sed ligula interdum vehicula. Nam eu nisl eget diam luctus aliquet ornare et leo. Sed vitae egestas turpis. Pellentesque ullamcorper porttitor elit, non laoreet felis tempus nec. Etiam mollis commodo urna, vitae faucibus dui dictum et. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vel mauris tellus. Nulla sed velit vel mauris gravida vehicula. Quisque dui lorem, euismod ut ornare et, venenatis ultricies sapien. Morbi laoreet, ante eu commodo faucibus, ipsum sapien adipiscing tortor, sed facilisis justo velit ut velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Suspendisse potenti. Maecenas leo dui, condimentum vel ornare ac, porttitor sit amet arcu. Aliquam imperdiet faucibus dapibus. Vivamus eu velit nunc, sit amet facilisis quam. Donec eleifend elementum luctus. Donec a metus ut metus aliquam scelerisque at sed libero. Mauris ante sapien, imperdiet id venenatis ac, mattis in est. Mauris condimentum, mi in gravida congue, mi tortor congue nulla, in lacinia purus neque vel diam. Fusce faucibus, tellus ac dictum imperdiet, dui nisi euismod purus, eget dapibus diam quam venenatis lectus. Fusce tempus iaculis aliquam. Sed non nisl ut ipsum facilisis adipiscing et in urna. Maecenas quis vestibulum turpis. Sed faucibus urna sed mauris iaculis volutpat. Aliquam sed est tellus, ut eleifend mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In justo sem, porta nec lacinia quis, elementum ac massa.

Nunc at nisi augue, et iaculis nisi. Integer condimentum blandit neque eu eleifend. Donec faucibus, enim vel fermentum tempus, purus orci blandit metus, non rhoncus mi sapien ac lacus. Donec congue dolor a neque pretium tempor. Ut vitae dui enim, euismod tempus risus. Nulla iaculis faucibus consequat. Quisque sed ornare nisl.

Pellentesque rutrum metus ac massa gravida pharetra nec et ante. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec eu enim vel dolor commodo mollis. Duis facilisis, erat in elementum elementum, massa sem condimentum nisl, a commodo augue odio sit amet neque. Etiam vitae nunc libero. Ut ac diam quis augue consequat imperdiet in nec ipsum. Vestibulum pulvinar tincidunt justo, non sagittis nisl suscipit ut. Vivamus fermentum nibh non justo convallis pretium. Aliquam rutrum iaculis convallis. Nulla pulvinar convallis orci porta ornare. Mauris vitae nulla purus, vel viverra libero. Aliquam erat volutpat.

labs/alienvspredator/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Alienvspredator</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="row">
    <div class="span12">
      <div class="navbar">
        <div class="navbar-inner">
          <a class="brand" href="#">Title</a>
          <ul class="nav">
            <li class="active"><%= link_to "Home", root_path %></li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
          </ul>
        </div>
      </div>
    </div><!-- end span12 -->
  </div><!-- end row -->
    <div class="row">
    <div class="span3">
      <%= yield :submenu %>
      <%= render 'shared/search' %>
    </div>
    <div class="span9">
      <%= yield %>
    </div>
  </div><!-- end row -->
  <div class="row">
    <div class="span12"></div>
  </div><!-- end row -->
</div><!-- end container -->

</body>
</html>