labs/mythology/config/routes.rb
Mythology::Application.routes.draw do
  resources :gods do
    collection do
      post 'search'
    end
  end

end

labs/mythology/app/models/god.rb
class God < ActiveRecord::Base
  attr_accessible :description, :name

  def self.text_search(query)
      self.where("name @@ :q or description @@ :q", :q => query)
  end
end

# @@ means INSIDE. :q is the QUERY.
# if the query = apollo, then it means
# "name INSIDE apollo or description INSIDE apollo"
# search here is advanced, it knows plurals, not case-sensitive, sounds like

labs/mythology/app/controllers/gods_controller.rb
  class GodsController < ApplicationController
  # GET /gods
  # GET /gods.json
  def index
    @gods = God.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gods }
    end
  end

  # GET /gods/1
  # GET /gods/1.json
  def show
    @god = God.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @god }
    end
  end

  # GET /gods/new
  # GET /gods/new.json
  def new
    @god = God.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @god }
    end
  end

  # GET /gods/1/edit
  def edit
    @god = God.find(params[:id])
  end

  # POST /gods
  # POST /gods.json
  def create
    @god = God.new(params[:god])

    respond_to do |format|
      if @god.save
        format.html { redirect_to @god, notice: 'God was successfully created.' }
        format.json { render json: @god, status: :created, location: @god }
      else
        format.html { render action: "new" }
        format.json { render json: @god.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gods/1
  # PUT /gods/1.json
  def update
    @god = God.find(params[:id])

    respond_to do |format|
      if @god.update_attributes(params[:god])
        format.html { redirect_to @god, notice: 'God was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @god.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gods/1
  # DELETE /gods/1.json
  def destroy
    @god = God.find(params[:id])
    @god.destroy

    respond_to do |format|
      format.html { redirect_to gods_url }
      format.json { head :no_content }
    end
  end

  def search
    query = params[:query]
    if query.present?
      @gods = God.text_search(query) # class method
    else
      @gods = God.all
    end
  end





end

labs/mythology/app/helpers/gods_helper.rb
module GodsHelper
end

labs/mythology/app/views/gods/_form.html.erb
<%= form_for(@god) do |f| %>
  <% if @god.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@god.errors.count, "error") %> prohibited this god from being saved:</h2>

      <ul>
      <% @god.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

labs/mythology/app/views/gods/_gods.html.erb
<h1>Listing gods</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% gods.each do |god| %>
  <tr>
    <td><%= god.name %></td>
    <td><%= god.description %></td>
    <td><%= link_to 'Show', god %></td>
    <td><%= link_to 'Edit', edit_god_path(god) %></td>
    <td><%= link_to 'Destroy', god, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New God', new_god_path %>

labs/mythology/app/views/gods/_search.html.erb
<%= form_tag '/gods/search', :id => 'searchform', :remote => true do %>
  <%= text_field_tag 'query' %>
  <!-- no submit button, submits on ENTER -->
<% end %>

labs/mythology/app/views/gods/edit.html.erb
<h1>Editing god</h1>

<%= render 'form' %>

<%= link_to 'Show', @god %> |
<%= link_to 'Back', gods_path %>

labs/mythology/app/views/gods/index.html.erb
<%= render 'search' %>

<div id="godlist">
<%= render :partial => 'gods', :locals => {:gods => @gods} %>
</div>

<!-- if you need to pass extra info, need to call partials with render :partial -->

labs/mythology/app/views/gods/new.html.erb
<h1>New god</h1>

<%= render 'form' %>

<%= link_to 'Back', gods_path %>

labs/mythology/app/views/gods/search.js.erb
$('#godlist').empty();
$('#godlist').append("<%=j render :partial => 'gods', :locals => {:gods => @gods} %>");
//put a j in front of code if the ruby in javascript isn't working

labs/mythology/app/views/gods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @god.name %>
</p>

<p>
  <b>Description:</b>
  <%= @god.description %>
</p>


<%= link_to 'Edit', edit_god_path(@god) %> |
<%= link_to 'Back', gods_path %>